# -*- coding: utf-8 -*-
"""TASK 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ztYbvghecP8mJMSMIfvFy_CekcLz3i2

1.Write a program that uses input to prompt a user for their name and then welcomes them.
"""

#please provide your answer here below this line
#PROGRAM-1
name = input("Please enter your name : ")
print("Welcome " + name);

"""2.Write a program which prompts the user for a Celsius temperature, convert the temperature to Fahrenheit, and print out the converted temperature."""

#please provide your answer here below this line
#PROGRAM-2
Celsius = float(input("Please enter temperature in Celsius : "))
Fahrenheit = (Celsius*1.8)+32
print("The temperature is : %.2f" %(Fahrenheit))

"""3.Write a Python program to convert degree to radian."""

#please provide your answer here below this line
#PROGRAM-3
degree = float(input("Please enter degree : "))
radian = degree*(3.14/180)
print("Radian is : %.2f" %(radian))